spring:
  profiles:
    active:
      - prod

# logging:
#  level:
#  org.hibernate.SQL: DEBUG
#  org.hibernate.type: TRACE
# org.springframework: DEBUG

---
spring:
  config:
    activate:
      on-profile:
        - dev
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 500
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    #      hibernate:
    #        show_sql: true
    #        use_sql_comments: true
    #        format_sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    generate-unique-name: false

  servlet:
    multipart:
      max-file-size: 10MB

pazarfy:
  upload-path: storage-dev/
  jwtSecretKey: secret-dev

---
spring:
  config:
    activate:
      on-profile:
        - prod
  datasource:
    url: jdbc:h2:./storage-prod/prodDB
    username: sa
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        # show_sql: true
        # use_sql_comments: true
        # format_sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 500

pazarfy:
  upload-path: storage-prod/
  jwtSecretKey: secret-prod
